import { Injectable, OnModuleInit } from '@nestjs/common';
// PrismaClient is generated by `npx prisma generate`.
import { PrismaClient } from '@prisma/client';
@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  async onModuleInit() {
    await this.$connect().catch(() => undefined);
  }
}
